### PR TITLE
feat(homepage): starting page (DEV-548)

### PR DESCRIPTION
**Pull request by mdelez**
resolves DEV-548

### CODE REVIEW

**Comment by mdelez** [comment]
@subotic @domsteinbach The method I found for doing this was to create separate `html` files for each "project". I didn't want to set up a SPA because I don't think that's really the point of this task and if I did that we would have a persistent navigation header. Instead the routing should be handled on the server side (I suppose that will be another task).

As it stands right now, the routes are:
`/dist/index.html` -> starting page
`/dist/playground.html` -> TailwindUI playground
`/dist/beol.html` -> Beol project page (currently empty)

**Review by domsteinbach — APPROVED** [review]
We could zhink of changing the Makefile in the future and output directly to html e.g. 

`elm make src/Beol.elm --output dist/beol.html --optimize`

where all the js will be included instead of outputting to js and having the html versioned. But we need to see how to apply the css file in that case (no idea atm).

**Comment by subotic** [comment]
hmm, the end goal would we to have ein App running, and have all the project pages render on the fly. So compiling project specific pages would break this end goal. A SPA can be whatever we decide it should be. It doesn't need to have the same navigation header on each and every page (I think). Or is there some limitation imposed by Elm?

**Comment by mdelez** [comment]
From what I could find a SPA in elm basically means that you have an `Main.elm` which is served via `index.html`. The `Main.elm` contains nothing more than a navigation header and a container with logic to look at changes to the url and display the corresponding view. We can discuss it on Monday in the Elm meeting.

**Comment by mdelez** [comment]
closed without merging, merged PR #23 instead

**Pull request closed without merging**
