### PR TITLE
chore: cleanup repository (DEV-447)

### PR DESCRIPTION
**Pull request by subotic**
resolves DEV-447

### CODE REVIEW

**Review by mdelez — APPROVED** [review]
Thanks!

**Review by kilchenmann — APPROVED** [review]
Does it make sense to keep `.vscode/` folder in git?

**Comment by mdelez** [comment]
> Does it make sense to keep `.vscode/` folder in git?

I can make a `gitignore` file as part of my task to make a playground

**Comment by subotic** [comment]
ok, now. add vscode and dist stuff to gitignore and removed it from the repository.

**Pull request merged**
